export const posts = [
  {
    name: 'Sandia National Lab',
    avatarUrl: 'https://logo.clearbit.com/sandia.gov',
    statusText: 'Now hiring New Grad roles in cybersecurity and systems engineering. \nApply now: https://cg.sandia.gov/psc/applicantions/',
    photo: require('../../assests/images/sandiaHiring.png'),
    likes: 128,
    comments: 12,
    shares: 4,
    time: '1 hour ago',
  },
  {
    name: 'Los Alamos Lab',
    avatarUrl: 'https://logo.clearbit.com/lanl.gov',
    statusText: 'Hiring Research roles across HPC, Software, and national security.',
    photo: require('../../assests/images/losAlamosHiring.png'),
    likes: 86,
    comments: 7,
    shares: 2,
    time: '1 day ago',
  },
  {
    name: 'Intel',
    avatarUrl: 'https://logo.clearbit.com/intel.com',
    statusText: 'Intel is coming to UNM for Hiring next week. \nCome and join us at SUB Ballroom.',
    photo: require('../../assests/images/intelHiring.png'),
    likes: 204,
    comments: 18,
    shares: 6,
    time: '1 day ago',
  },
  {
    name: 'Microsoft',
    avatarUrl: 'https://logo.clearbit.com/microsoft.com',
    statusText: 'New Grad roles in cloud, AI, and Software. \nApply now: https://microsoft.com/applicantions/',
    photoUrl:
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=60',
    likes: 143,
    comments: 21,
    shares: 5,
    time: '4 hrs ago',
  },
  {
    name: 'Apple',
    avatarUrl: 'https://logo.clearbit.com/apple.com',
    statusText: 'Apple is hiring across iOS, macOS, and silicon chips.',
    photoUrl:
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=60',
    likes: 178,
    comments: 25,
    shares: 7,
    time: '4 hrs ago',
  },
  {
    name: 'Sandia National Lab',
    avatarUrl: 'https://logo.clearbit.com/sandia.gov',
    statusText: 'Now hiring interns in Software and systems engineering.',
    photo: require('../../assests/images/sandiaNewHiring.png'),
    likes: 128,
    comments: 12,
    shares: 4,
    time: '1 hour ago',
  },
  {
    name: 'Los Alamos Lab',
    avatarUrl: 'https://logo.clearbit.com/lanl.gov',
    statusText: 'Los Alamos is coming to UNM for Hiring next week on 10th November.',
    likes: 86,
    comments: 7,
    shares: 2,
    time: '1 day ago',
  },
];
