const candidates = [
  {
    id: 1,
    name: "Aria Montgomery",
    title: "Senior AI Engineer",
    location: "San Francisco, CA",
    match: 92,
    tags: ["Python", "TensorFlow", "NLP", "PyTorch"],
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: 2,
    name: "Ken Alvarez",
    title: "Machine Learning Specialist",
    location: "New York, NY",
    match: 75,
    tags: ["Scikit-learn", "Pandas", "Data Visualization"],
    avatar: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    id: 3,
    name: "Hanna Marin",
    title: "AI Research Scientist",
    location: "Boston, MA",
    match: 62,
    tags: ["Python", "Research", "Algorithms"],
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    id: 4,
    name: "Ethan Walker",
    title: "Computer Vision Engineer",
    location: "Seattle, WA",
    match: 88,
    tags: ["OpenCV", "Deep Learning", "C++", "PyTorch"],
    avatar: "https://randomuser.me/api/portraits/men/58.jpg",
  },
  {
    id: 5,
    name: "Maya Patel",
    title: "Data Scientist",
    location: "Austin, TX",
    match: 79,
    tags: ["Python", "SQL", "Machine Learning", "Tableau"],
    avatar: "https://randomuser.me/api/portraits/women/57.jpg",
  },
  {
    id: 6,
    name: "Leo Kim",
    title: "NLP Research Engineer",
    location: "Los Angeles, CA",
    match: 68,
    tags: ["Transformers", "Hugging Face", "BERT", "Python"],
    avatar: "https://randomuser.me/api/portraits/men/62.jpg",
  },
];